site_name: Glaze
repo_url: https://github.com/font-bakers/glaze
nav:
    - Home: index.md
    - Quickstart: quickstart.md
    - Contributing: contributing.md
    - About:
      - Code of Conduct: https://github.com/font-bakers/glaze/blob/master/CODE_OF_CONDUCT.md
      - License: https://github.com/font-bakers/glaze/blob/master/LICENSE
theme: readthedocs
